/**
 * Galaxy Open-Source Massively Multiplayer Game Simulation Engine
 * Copyright (C) 2007 OpenSWG Team <http://www.openswg.com>
 */

// *********************************************************************
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// To read the license please visit http://www.gnu.org/copyleft/gpl.html
// *********************************************************************

#ifndef OPENSWG_SOEPROTOCOL_MOODS
#define OPENSWG_SOEPROTOCOL_MOODS

namespace osSOEProtocol
{
	const static std::string MoodStr[]= {
    "none",
    "absentminded",
    "amazed",
    "amused",
    "angry",
    "approving",
    "bitter",
    "bloodthirsty",
    "brave",
    "callous",
    "careful",
    "careless",
    "casual",
    "clinical",
    "cocky",
    "cold",
    "compassionate",
    "condescending",
    "confident",
    "confused",
    "content",
    "courtly",
    "coy",
    "crude",
    "cruel",
    "curious",
    "cynical",
    "defensive",
    "depressed",
    "devious",
    "dimwitted",
    "disappointed",
    "discreet",
    "disgruntled",
    "disgusted",
    "dismayed",
    "disoriented",
    "distracted",
    "doubtful",
    "dramatic",
    "dreamy",
    "drunk",
    "earnest",
    "ecstatic",
    "embarrassed",
    "emphatic",
    "encouraging",
    "enthusiastic",
    "evil",
    "exasperated",
    "exuberant",
    "fanatical",
    "forgive",
    "frustrated",
    "guilty",
    "happy",
    "honest",
    "hopeful",
    "hopeless",
    "humble",
    "hysterical",
    "imploring",
    "indifferent",
    "indignant",
    "interested",
    "jealous",
    "joyful",
    "lofty",
    "loud",
    "loving",
    "lustful",
    "mean",
    "mischievous",
    "nervous",
    "neutral",
    "offended",
    "optimistic",
    "pedantic",
    "pessimistic",
    "petulant",
    "philosophical",
    "pitying",
    "playful",
    "polite",
    "pompous",
    "proud",
    "provocative",
    "puzzled",
    "regretful",
    "relieved",
    "reluctant",
    "resigned",
    "respectful",
    "romantic",
    "rude",
    "sad",
    "sarcastic",
    "scared",
    "scolding",
    "scornful",
    "serious",
    "shameless",
    "shocked",
    "shy",
    "sincere",
    "sleepy",
    "sly",
    "smug",
    "snobby",
    "sorry",
    "spiteful",
    "stubborn",
    "sullen",
    "suspicious",
    "taunting",
    "terrified",
    "thankful",
    "thoughtful",
    "tolerant",
    "uncertain",
    "unhappy",
    "unwilling",
    "warm",
    "whiny",
    "wicked",
    "wistful",
    "worried",
    "tired",
    "exhausted",
    "friendly",
    "timid",
    "lazy",
    "surprised",
    "innocent",
    "wise",
    "youthful",
    "adventurous",
    "annoyed",
    "perturbed",
    "sedate",
    "calm",
    "suffering",
    "hungry",
    "thirsty",
    "alert",
    "shifty",
    "relaxed",
    "crotchety",
    "surly",
    "painful",
    "wounded",
    "bubbly",
    "heroic",
    "quiet",
    "remorseful",
    "grumpy",
    "logical",
    "emotional",
    "troubled",
    "panicked",
    "nice",
    "cheerful",
    "emotionless",
    "gloomy",
    "ambivalent",
    "envious",
    "vengeful",
    "fearful",
    "enraged",
    "sheepish",
    "belligerent",
    "obnoxious",
    "fastidious",
    "squeamish",
    "dainty",
    "dignified",
    "haughty",
    "obscure",
    "goofy",
    "silly",
    "disdainful",
    "contemptuous",
    "diplomatic",
    "wary",
    "malevolent",
    "hurried",
    "patient",
    "firm",

};
	
}

#endif // OPENSWG_SOEPROTOCOL_MOODS

